//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int cedula { get; set; }
        public string nombre { get; set; }
        public string p_apellido { get; set; }
        public string s_apellido { get; set; }
        public string edad { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string correo { get; set; }
        public string passw { get; set; }
        public string rol { get; set; }
    }
}
