//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class listaEspera
    {
        public long codigo_barras { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> porcion { get; set; }
        public Nullable<double> energia { get; set; }
        public Nullable<double> grasa { get; set; }
        public Nullable<double> sodio { get; set; }
        public Nullable<double> carbohidratos { get; set; }
        public Nullable<double> proteina { get; set; }
        public string vitaminas { get; set; }
        public Nullable<double> calcio { get; set; }
        public Nullable<double> hierro { get; set; }
        public string nutri_correo { get; set; }
        public Nullable<int> lista_espera { get; set; }
    }
}
