//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class meta_calorica
    {
        public int id_meta { get; set; }
        public System.DateTime fecha_meta { get; set; }
        public int meta_calorias_dia { get; set; }
        public Nullable<int> calorias_logradas { get; set; }
        public Nullable<int> cliente_cedula { get; set; }
        public Nullable<int> nutricionista_cedula { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual nutricionista nutricionista { get; set; }
    }
}
