//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutriTECEntities : DbContext
    {
        public NutriTECEntities()
            : base("name=NutriTECEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cliente_nutricionista> cliente_nutricionista { get; set; }
        public virtual DbSet<cuentas> cuentas { get; set; }
        public virtual DbSet<meta_calorica> meta_calorica { get; set; }
        public virtual DbSet<nutricionista> nutricionista { get; set; }
        public virtual DbSet<producto> producto { get; set; }
    }
}
