//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class nutricionista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nutricionista()
        {
            this.meta_calorica = new HashSet<meta_calorica>();
        }
    
        public int n_cedula { get; set; }
        public string nombre { get; set; }
        public string p_apellido { get; set; }
        public string s_apellido { get; set; }
        public string codigo { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string peso { get; set; }
        public Nullable<double> IMC { get; set; }
        public string direccion { get; set; }
        public string foto { get; set; }
        public Nullable<int> tarjetacredito { get; set; }
        public string tipo_cobro { get; set; }
        public string correo { get; set; }
        public string passw { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meta_calorica> meta_calorica { get; set; }
    }
}
