//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public int id { get; set; }
        public int n_cedula { get; set; }
        public int paciente_cedula { get; set; }
        public Nullable<int> paciente_plan { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual nutricionista nutricionista { get; set; }
        public virtual plan_alimenticio plan_alimenticio { get; set; }
    }
}
