//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.productosXplan = new HashSet<productosXplan>();
        }
    
        public long codigo_barras { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> porcion { get; set; }
        public Nullable<double> energia { get; set; }
        public Nullable<double> grasa { get; set; }
        public Nullable<double> sodio { get; set; }
        public Nullable<double> carbohidratos { get; set; }
        public Nullable<double> proteina { get; set; }
        public string vitaminas { get; set; }
        public Nullable<double> calcio { get; set; }
        public Nullable<double> hierro { get; set; }
        public Nullable<int> lista_espera { get; set; }
        public Nullable<int> nutri_cedula { get; set; }
        public string nutri_correo { get; set; }
    
        public virtual nutricionista nutricionista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productosXplan> productosXplan { get; set; }
        public virtual registro_comida registro_comida { get; set; }
    }
}
