//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class productosXplan
    {
        public long codigo_barras { get; set; }
        public string descripcion { get; set; }
        public double energia { get; set; }
        public string tiempo_comida { get; set; }
        public int plan_pertenece { get; set; }
        public int cantidad { get; set; }
    
        public virtual plan_alimenticio plan_alimenticio { get; set; }
        public virtual producto producto { get; set; }
    }
}
