//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int codigo_barras { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> porcion { get; set; }
        public Nullable<int> energia { get; set; }
        public Nullable<int> grasa { get; set; }
        public Nullable<int> sodio { get; set; }
        public Nullable<int> carbohidratos { get; set; }
        public Nullable<int> proteina { get; set; }
        public string vitaminas { get; set; }
        public Nullable<int> calcio { get; set; }
        public Nullable<int> hierro { get; set; }
        public Nullable<int> lista_espera { get; set; }
        public Nullable<int> nutri_cedula { get; set; }
        public string nutri_correo { get; set; }
    
        public virtual nutricionista nutricionista { get; set; }
    }
}
