//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class productosXreceta
    {
        public long codigo_barras { get; set; }
        public string descripcion { get; set; }
        public double energia { get; set; }
        public int id_receta { get; set; }
        public int cliente_cedula { get; set; }
        public int cantidad { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual Recetas Recetas { get; set; }
    }
}
