//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriTEC_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int id { get; set; }
        public string nombre_receta { get; set; }
        public Nullable<double> energía { get; set; }
        public Nullable<double> grasa { get; set; }
        public Nullable<double> sodio { get; set; }
        public Nullable<double> carbohidratos { get; set; }
        public Nullable<double> proteinas { get; set; }
        public Nullable<int> cliente_creador { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
